### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by Sinitra** [mat-sz/filedrop-web#14]
Can you please share your ssl settings? Although I tried many methods, it persistently wants to work in http mode. I think there are parts I missed. Thanks. By the way, your project rock!

**Comment by rehanone** [comment]
Hello, this project looks awesome and I am really in love with how simple it looks. However I have been trying to get it working behind a tls connection for past 2 days using multiple reverse proxies and nginx. So far I failed to make it work. It just hangs on connecting page and that's it. I know this is an older question and may not get answered. I just hope someone could share their nginx config. Anyway, many thanks in advance.

**Comment by mat-sz** [comment]
@Sinitra @rehanone You need to reverse proxy the WebSocket app through nginx.

More details: https://www.nginx.com/blog/websocket-nginx/

```nginx

# ...
    upstream filedrop {
	server 127.0.0.1:5000;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        server_name drop.lol;
        error_page 404 /403.html;
	error_page 403 /403.html;

	location ~* \.(js|css)$ {
		root /home/node/filedrop-web/build;
		expires 1M;
		add_header Cache-Control "public immutable";
	}

	location /ws/ {
	    proxy_pass http://filedrop;
	    proxy_http_version 1.1;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header Host $host;
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection $connection_upgrade;
	}

	location = /403.html {
		root /srv/http;
		allow all;
		internal;
	}

	location / {
	    root /home/node/filedrop-web/build;
	    try_files $uri $uri/ /index.html;
	    index index.html;
	}

	location = /index.html {
		index index.html;
		expires 0;
		add_header Cache-Control no-cache;
		root /home/node/filedrop-web/build;
	}

        listen 443 ssl http2; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/drop.lol/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/drop.lol/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }

# ...
```

**Comment by rehanone** [comment]
@mat-sz Thank you for sharing your config. I tries it using the the docker-compose setup but still could not get it to work. The UI just gets hung up with message `Connecting`. It looks like your nginx file is based on a deployment without docker though. I will give that a try over the weekend. But I have no experience of working with node apps so I am not sure if that will work out so well. Regardless I think your app is the only one that looks promising. i have looked at using https://file.pizza but it looks like that has been abandoned by the devs.

**Comment by mat-sz** [comment]
@rehanone I've updated the filedrop-docker README to better reflect the possibilities of such deployment.

https://github.com/mat-sz/filedrop-docker

Please reopen the issue if that does not solve your problem.

**Comment by rehanone** [comment]
@mat-sz , Thank you! It turned out my issue was this like in the compose file
`REACT_APP_SERVER=ws://${HOST}:${PORT}/ws/`
as soon as I changed it to `wss://`, everything started working. But in the process I have done a lot of work to get the Traefik proxy up and running. However, there are cases which are still not working I think they are related to to nginx redirects specifically:
`try_files $uri $uri/ /index.html;`

Once I get it all working, I will provide an example if someone is interested in hosting it behind Traefik.

Also, is there any plans for publishing this web and ws images to docker hub? I was going to publish them but I thought maybe you have some plan for it already.

Regards and many thanks for creating this awesome utility!

**Comment by mat-sz** [comment]
@rehanone Thanks!

> Thank you! It turned out my issue was this like in the compose file
> `REACT_APP_SERVER=ws://${HOST}:${PORT}/ws/`

I've added that to the README in filedrop-docker.

> However, there are cases which are still not working I think they are related to to nginx redirects specifically:
> `try_files $uri $uri/ /index.html;`

I believe this to be an issue with me using the development server from React instead of hosting the files, I'll take a look on how to improve that.

> Also, is there any plans for publishing this web and ws images to docker hub? I was going to publish them but I thought maybe you have some plan for it already.

No plans from my side, feel free to maintain an image if you wish, make sure it's clearly marked as unofficial, though.

**Comment by mat-sz** [comment]
@rehanone I've updated the nginx configuration in filedrop-docker to be more in line with what I'm using in the production environment. This should help remedy the issues.

**Comment by mat-sz** [comment]
@rehanone I've enabled discussions.

Also, `git submodule update --remote` should be enough to update the submodules. As for versioning, I was thinking of adding it but I don't believe it to be useful enough to be worth the extra effort.

**Comment by rehanone** [comment]
Well I need to come up with some kind of versioning system to tag it on docker hub. I will see if I can make a PR for it. Thanks
